spring:
  application:
    name: CiTiFier

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/pg
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    dbcp2:
      default-schema: ${db.schemaName}

  liquibase:
    change-log: db/changelog/changelog-master.yaml
    default-schema: ${db.schemaName}

preliquibase:
  sql-script-references: classpath:/db/preliquibase/schema-creation.sql

logging:
  level:
    org:
      springframework.security: TRACE

db:
  schemaName: ctf

kubernetess:
  cluster-config-path:
  docker-context:
    minikube-context: true
    DOCKER_TLS_VERIFY: 1
    DOCKER_HOST: tcp://127.0.0.1:52452
    DOCKER_CERT_PATH: C:\Users\kamil\.minikube\certs
    MINIKUBE_ACTIVE_DOCKERD: minikube

oauth2:
  github:
    client-id:
    client-secret:
    app-id:

repo:
    base-file-path: D:\\CLONED_REPO_CITIFIER

docker:
  build:
    shell:
      name: powershell.exe
      config: -Command
