kubernetess:
  cluster-config-path:
  docker-context:
    DOCKER_TLS_VERIFY: 1
    DOCKER_HOST: tcp://127.0.0.1:60177
    DOCKER_CERT_PATH: C:\Users\kamil\.minikube\certs
    MINIKUBE_ACTIVE_DOCKERD: minikube

docker:
  build:
    shell: powershell.exe
    config: -Command
    command: "docker-compose build"

repo:
  base-file-path: D:\\CLONED_REPO_CITIFIER