name: Java build with Gradle

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4
    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
    - name: Setup gradle 
      uses: gradle/gradle-build-action@v2
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Run and build
      run: ./gradlew build

